Repository unisg-scs-se/SCS-SE-FS24-Experiments, pull requests merged in 2024-01, with the labels that each got.

#1 Feature xy
  src/main/java/com/example/bookexample/service/BookServiceImpl.java
Labels: enhancement

#2 Feature yz
  README.md
Labels: bug

#3 Library Extension Branch added
  src/main/java/com/example/bookexample/model/Book.java
Labels: enhancement

#4 cosmetic change
  README.md
Labels: documentation
